### PR TITLE
Add support for posts-2-posts link duplication

### PR DESCRIPTION
**Pull request by ichernev**
[posts-2-posts](https://wordpress.org/plugins/posts-to-posts/) is a plugin that lets you connect post types to one another.

With this addon for MPD, I'm making it possible to copy those links across sites, if the linked posts are duplicated with MPD.

There is no admin checkbox for this yet :D so its always-on

### CODE REVIEW

**Comment by magicstickuk** [comment]
Hey dude. Looks awesome and happy to apply. Can you wrap this in some suitable logic so we don't try to run this code if your plugin isn't active on the network?

**Comment by ichernev** [comment]
It has logic, that checks `function_exists` for p2p, I'm not sure if that is enough or there needs to be additional checks. `is_plugin_active` might be an option, but not sure how to use it (it says only frontend/admin, I guess I need to check for that first).

**Comment by ichernev** [comment]
Ah, my bad, I'll use https://codex.wordpress.org/Function_Reference/is_plugin_active_for_network

**Comment by ichernev** [comment]
Is there anything else I should do here?

**Comment by magicstickuk** [comment]
HIi ichernev. sorry for the delay on getting back to you on this. I added your code and did some testing. I was getting a few fatal errors on activation and had a look at trying to fix, but it made me realise that I think this code is best suited to be managed by yourself. Maybe submit it to Wordpress as a plugin as an extension to your plugin?

**Comment by ichernev** [comment]
@magicstickuk if all the extension points are available I can try. posts-2-posts is not my plugin, I just happen to use mpd and p2p both.

What kind of fatal errors are you talking about?

**Pull request merged**
